# Generated by Django 5.0.7 on 2025-04-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetriapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Dose',
        ),
        migrations.RemoveField(
            model_name='product',
            name='benifits',
        ),
    ]
