# Generated by Django 5.0.7 on 2026-04-18 03:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriapp', '0002_remove_product_dose_remove_product_benifits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, help_text='Enter one description per line with icons (e.g. 📱, 📶, ⚡...)'),
            preserve_default=False,
        ),
    ]
